FROM node:20-alpine AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

# stage 2 run

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/build /app/build

COPY server.js /app/server.js

EXPOSE 3000

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["node", "server.js"]