name: deploy pipeline

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'the git commit sha of the ecr image'
        required: true 
    
env:
  
  AWS_REGION : "eu-west-2" 

permissions:
      id-token: write  
      contents: read    
jobs:  
  terraform-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:


      - name: Checkout repo
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
  
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v4 
        
      - name: terraform init  
        run: terraform init
        working-directory: infra
      
      - name: terraform validate
        run: terraform validate
        working-directory: infra
      
      - name: terraform plan 
        run: terraform plan -var="image_tag=${{ github.event.inputs.image_tag }}" -out=tfplan
        working-directory: infra

      - name: terraform apply  
        run: terraform apply tfplan
        working-directory: infra





        
